### PR TITLE
Fix Object Cache Pro compatibility issue

### LINKED ISSUE #95: Fatal error when using Object Cache Pro
### Describe the bug

When attempting to generate the index for this plugin, I get the following error:

```
Error: Thrown Error (500): Cannot access protected property RedisCachePro\ObjectCaches\RelayObjectCache::$cache in /wp-content/plugins/block-catalog/includes/utility.php:87
```

According to WordPress, plugin authors should "not use the class directly in your code when writing plugins, but use the `wp_cache_*` functions" instead:

https://developer.wordpress.org/reference/classes/wp_object_cache/#role-of-the-wordpress-object-cache

This is an issue with the [Object Cache Pro](https://objectcache.pro/) plugin, but I assume it may present issues with other object cache drop-ins.

### Steps to Reproduce

1. Install and enable the plugin on a WordPress instance that is using Object Cache Pro
2. Attempt to index Post and / or Page content
3. See the fatal error

### Screenshots, screen recording, code snippet

Image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by heyjones**
### Description of the Change
- Replace direct access to object cache properties with WordPress's `wp_cache_*` functions
- This fixes the fatal error when using Object Cache Pro or other object cache drop-ins
- Follows WordPress best practices for plugin development
- Add test to ensure clear_caches function works without errors

Closes #95

### How to test the Change

- Install and activate Object Cache Pro and Block Catalog plugins
- Trigger a block index
- See that indexing occurs without incident

### Changelog Entry

> Fixed - Fatal error accessing object cache properties that may be protected/private in drop-ins.

### Credits

Props @heyjones, @stevenwareham

### Checklist:

- [X] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [X] I have updated the documentation accordingly.
- [X] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [X] All new and existing tests pass.

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
Thanks for the pull request @heyjones.

I've got a copy of OCP that I can test with locally so I will do so today. 

Flushing the runtime cache seems much more sensible than flushing the object cache, but I'd like to take a look at whether the plugin should be more targeted with what parts of the cache are cleared during the bulk updates.

**Comment by heyjones** [comment]
> Thanks for the pull request @heyjones.
> 
> I've got a copy of OCP that I can test with locally so I will do so today.
> 
> Flushing the runtime cache seems much more sensible than flushing the object cache, but I'd like to take a look at whether the plugin should be more targeted with what parts of the cache are cleared during the bulk updates.

Sounds great, thanks really appreciate it!

File: includes/utility.php [hunk 1]
```diff
@@ -76,19 +76,22 @@ function stop_bulk_operation() {
...
+		wp_cache_flush();
+	}
 
-		if ( method_exists( $wp_object_cache, '__remoteset' ) ) {
-			$wp_object_cache->__remoteset(); // important
-		}
+	// Reset any custom cache stats if the object cache supports it
+	if ( function_exists( 'wp_cache_stats' ) ) {
+		wp_cache_stats();
 	}
```
Comment (peterwilsoncc) [inline includes/utility.php]:
```suggestion
```

The implementations of `wp_cache_stats()` that I could find use this as a getter, so I don't think this is doing what is intended here.

As it's a relatively small amount of data (number of reads, writes), I think it's fine to leave the data uncleared.

**Review by peterwilsoncc — CHANGES_REQUESTED** [review]
This is testing well, I can reproduce the fatal error on the `develop` branch and it is resolved on this branch.

I think flushing the runtime cache only if it's supported is a great idea, thanks for doing that.

Re my earlier comment, I think there is room for improvement but it will require a little more research so let's keep this PR focused on fixing the fatal error and I'll create a follow up ticket that may allow us to avoid flushing the cache.

I've put minor change request inline but feel free to push back if I am misunderstanding something.

**Comment by heyjones** [comment]
> This is testing well, I can reproduce the fatal error on the `develop` branch and it is resolved on this branch.
> 
> I think flushing the runtime cache only if it's supported is a great idea, thanks for doing that.
> 
> Re my earlier comment, I think there is room for improvement but it will require a little more research so let's keep this PR focused on fixing the fatal error and I'll create a follow up ticket that may allow us to avoid flushing the cache.
> 
> I've put minor change request inline but feel free to push back if I am misunderstanding something.

Makes sense, I think that was Cursor hallucinating.

**Comment by heyjones** [comment]
> > This is testing well, I can reproduce the fatal error on the `develop` branch and it is resolved on this branch.
> > I think flushing the runtime cache only if it's supported is a great idea, thanks for doing that.
> > Re my earlier comment, I think there is room for improvement but it will require a little more research so let's keep this PR focused on fixing the fatal error and I'll create a follow up ticket that may allow us to avoid flushing the cache.
> > I've put minor change request inline but feel free to push back if I am misunderstanding something.
> 
> Makes sense, I think that was Cursor hallucinating.

I think this is what it was attempting to do:

https://github.com/rhubarbgroup/wp-object-cache-info-spec?tab=readme-ov-file#wp_cache_reset_stats

**Review by peterwilsoncc — APPROVED** [review]
Thanks Chris, this looks good.

I'll merge it in to the develop branch and we'll include the fix in the next release.

**Comment by heyjones** [comment]
> Thanks Chris, this looks good.
> 
> I'll merge it in to the develop branch and we'll include the fix in the next release.

@peterwilsoncc do you know when the next plugin release will be? Planning on using this to assist with some prep work for a content migration. Thanks again!
